### ISSUE TITLE
#6 Accessibility on different devices

### ISSUE THREAD

**Issue by zihao429** [JamesPartsafas/soen390#44]
As a user, I want to access the application on different operating systems, so I can use different devices for Synapsis.

Story Points: 1
MoSCoW: Should
Business Value: M
Risk: Low

Acceptance Criteria
Given I’m a logged-in or logged-out system user
When I land on the website
Then the website is accessible on all operating systems: Windows, MacOS, Linux, etc.

**Comment by janong24** [comment]
Site responsive as per previous commits.
