### ISSUE TITLE
#8.1 App in English

### ISSUE THREAD

**Issue by zihao429** [JamesPartsafas/soen390#47]
As a user, I want to be able to access the app in English, so that I can read the website in English.

Story Points: 2
MoSCoW: Could
Business Value: L
Risk: Low

Acceptance Criteria
Given I’m a logged-in or logged-out system user
When I scroll down to the footer of the page, and click on the “Language” icon button where I select “English”
Then the system displays all text in English for the application

Child of #46

**Comment by janong24** [comment]
Epic closed.
