### ISSUE TITLE
#8.2 App in French

### ISSUE THREAD

**Issue by zihao429** [JamesPartsafas/soen390#48]
As a user, I want to be able to access the app in French, so that I can read the website in French.

Story Points: 2
MoSCoW: Could
Business Value: L
Risk: Low

Acceptance Criteria
Given I’m a logged-in or logged-out system user
When I scroll down to the footer of the page, and click on the “Language” icon button, where I select “French”
Then the system displays all text in French for the application

Child of #46

**Comment by janong24** [comment]
Epic closed.
