### ISSUE TITLE
#1.4 Login

### ISSUE THREAD

**Issue by kennyphan100** [JamesPartsafas/soen390#56]
As a user, I want to be able to login with my account, so that I can use Synapsis with an account.

Story Points: 1
MoSCoW: Must
Business Value: XL
Risk: Medium

Acceptance Criteria
- Upon landing on the website, go to the log-in page
- Input the valid required information (email & password) to log-in into the account
- A confirmation message will be displayed on the page

Child of #19

**Comment by JamesPartsafas** [comment]
Implemented by PR #15
